version: 0.1.{build}.0
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
clone_depth: 1
clone_folder: c:\projects\gfoidl
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- cmd: >-
    dotnet restore

    dotnet build -c Release --no-restore

    dotnet pack -o c:\projects\gfoidl\NuGet-Packed --no-build -c Release source\gfoidl.Base64
test_script:
- ps: >-
    dotnet test -c Release --no-build --logger "trx;LogFileName=testresult.xml" tests\gfoidl.Base64.Tests\gfoidl.Base64.Tests.csproj

    $testExit = $lastExitCode

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", "C:\projects\gfoidl\tests\gfoidl.Base64.Tests\TestResults\testresult.xml")

    if ($testExit) {
      exit 1;
    }
artifacts:
- path: NuGet-Packed\*.nupkg
  name: NuGet
on_finish:
- cmd: dir .\NuGet-Packed
